name: XAU Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          pip install yfinance
          pip install pandas requests
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python live.py
